BASE_URL = "https://www.tobeto.com"
FIRST_LOGIN_BUTTON = ".border-light"
EMAIL_NAME = "email"
PASSWORD_NAME = "password"
LOGIN_BUTTON_XPATH = "//button[@class='btn btn-primary w-100 mt-6']"
LOGIN_MESSAGE_CSS = "div[class='toast-body']"
ERROR_MESSAGE_CSS = "div[class='toast-body']"
ERROR_MESSAGE_XPATH = "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/p"
FIRST_REGISTER_BUTTON = "//a[@href='/kayit-ol']"
NAME_NAME = "firstName"
SURNAME_NAME = "lastName"
ENTER_EMAIL = "email"
ENTER_PASSWORD = "password"
PASSWORD_AGAIN = "passwordAgain"
REGISTER_BUTTON_XPATH = "//button[@class='btn btn-primary w-100 mt-6']"
EXPLICIT_CONSENT_CHECKBOX = "contact"
MEMBERSHIP_CONTRAT_CHECKBOX = "membershipContrat"
EMAIL_CONFIRMATION_CHECKBOX = "emailConfirmation"
PHONE_CONFIRMATION_CHECKBOX = "phoneConfirmation"
ENTER_PHONE = "phoneNumber"
IFRAME_XPATH = "/html/body/div[4]/div/div/div/div/div/div[2]/div/div/div/iframe"
RECAPTCHA_CHECKBOX = "//div[@class='recaptcha-checkbox-border']"
CONTINUE_BUTTON_CSS = ".alert-buttons"
REGISTER_MESSAGE = "span[class='success-payment-text']"
INVALID_EMAIL_MESSAGE = "//p[.='Geçersiz e-posta adresi*']"
INVALID_PHONE_MESSAGE = "/html/body/div[4]/div/div/div/div/div/label[4]/small/p"
INVALID_PHONE_MESSAGE2 = "//p[.='En fazla 10 karakter girebilirsiniz.']"