BASE_URL = "https://www.tobeto.com"
LOGIN_URL = "https://tobeto.com/giris"
FIRST_LOGIN_BUTTON = ".border-light"
EMAIL_NAME = "email"
PASSWORD_NAME = "password"
LOGIN_BUTTON_XPATH = "//button[@class='btn btn-primary w-100 mt-6']"
LOGIN_MESSAGE_CSS = "div[class='toast-body']"
ERROR_MESSAGE_CSS = "div[class='toast-body']"
ERROR_MESSAGE_XPATH = "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/p"
FIRST_REGISTER_BUTTON = "//a[@href='/kayit-ol']"
NAME_NAME = "firstName"
SURNAME_NAME = "lastName"
ENTER_EMAIL = "email"
ENTER_PASSWORD = "password"
PASSWORD_AGAIN = "passwordAgain"
REGISTER_BUTTON_XPATH = "//*[@id='__next']/div/main/section/div/div/div[1]/div/div/button"
EXPLICIT_CONSENT_CHECKBOX = "contact"
MEMBERSHIP_CONTRAT_CHECKBOX = "membershipContrat"
EMAIL_CONFIRMATION_CHECKBOX = "emailConfirmation"
PHONE_CONFIRMATION_CHECKBOX = "phoneConfirmation"
ENTER_PHONE = "phoneNumber"
IFRAME_XPATH = "/html/body/div[4]/div/div/div/div/div/div[2]/div/div/div/iframe"
RECAPTCHA_CHECKBOX = "//div[@class='recaptcha-checkbox-border']"
CONTINUE_BUTTON_XPATH = "/html/body/div[4]/div/div/div/div/div/div[3]/button[2]"
REGISTER_MESSAGE = "span[class='success-payment-text']"
INVALID_EMAIL_MESSAGE = "//p[.='Geçersiz e-posta adresi*']"
INVALID_PHONE_MESSAGE = "/html/body/div[4]/div/div/div/div/div/label[4]/small/p"
INVALID_PHONE_MESSAGE2 = "//p[.='En fazla 10 karakter girebilirsiniz.']"
REGISTERED_EMAIL_MESSAGE = "toast-body"
PASSWORD_ERROR_MESSAGE = "toast-body"
NON_MATCHING_PASSWORDS = "toast-body"
TWO_ERRORS_MESSAGE = "toast-body"
SIGN_UP_MAIL_XPATH = "//*[@id='__next']/div/main/section/div/div/div/input"
SEND_BUTTON_XPATH = "//*[@id='__next']/div/main/section/div/div/div/button"
SYSTEM_MESSAGE_XPATH = "//*[@id='__next']/div/main/div[2]/div/div[2]"
PASSWORD_RESET_BUTTON = "//p[@class='text-decoration-none text-muted mt-5 d-block']"
ERROR_MESSAGE = "//*[@id='__next']/div/main/div[2]/div/div[2]"
IFRAME_ID = "exw-launcher-frame"
LAUNCHER_BUTTON = "launcher"
TOBETO_MESSAGE = "//section[@class='position-relative py-lg-20 bg-light-light py-sm-10']"
IFRAME_MESSAGE_BOX = "iframe[class='exw-conversation-container-frame']"
MINIMIZE_ICON = "svg[class='exw-minimize-button header-button']"
IFRAME_CSS = "iframe[class='exw-launcher-frame animated swing']"
CHATBOT_BUTTON = "button[id='launcher']"
IFRAME_END_CHAT = "exw-conversation-frame"
END_CHAT_BUTTON = "//*[name()='svg' and @class='exw-end-session-button header-button']"
END_CHAT_BOX = "h4[class='exw-title exw-with-avatar']"